# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- prod

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npx kendo-ui-license activate
  displayName: 'Activate Kendo UI License'
  env:
    KENDO_UI_LICENSE: $(KENDO_UI_LICENSE)

- script: |
    npx nx run front-office:build:azure-prod
    npx nx run back-office:build:azure-prod
  displayName: 'build the apps'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/apps/front-office'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/prod/front-office/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/apps/back-office'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/prod/back-office/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/prod/front-office/$(Build.BuildId).zip'
    ArtifactName: 'prod-front-office'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/prod/back-office/$(Build.BuildId).zip'
    ArtifactName: 'prod-back-office'
    publishLocation: 'Container'
