/* eslint-disable */
export default {
  displayName: 'shared',
  preset: '../../jest.preset.js',
  setupFiles: [`../../jest-shim.ts`],
  setupFilesAfterEnv: ['<rootDir>/src/test-setup.ts'],
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.spec.json',
      stringifyContentPathRegex: '\\.(html|svg)$',
    },
  },
  coverageDirectory: '../../coverage/libs/shared',
  transform: {
    '^.+\\.(ts|mjs|js|html)$': 'jest-preset-angular',
  },
  transformIgnorePatterns: [
    'node_modules/(?!.*\\.mjs$)',
    '<rootDir>/node_modules/(?!lodash-es)',
  ],
  snapshotSerializers: [
    'jest-preset-angular/build/serializers/no-ng-attributes',
    'jest-preset-angular/build/serializers/ng-snapshot',
    'jest-preset-angular/build/serializers/html-comment',
  ],
  moduleNameMapper: {
    '^lodash-es$': 'lodash',
  },
  // Manually add valid tests there
  testMatch: [
    '<rootDir>/src/lib/services/auto-translate/*.spec.ts',
    '<rootDir>/src/lib/services/context/*.spec.ts',
    '<rootDir>/src/lib/services/file/*.spec.ts',
    '<rootDir>/src/lib/services/form-helper/*.spec.ts',
    '<rootDir>/src/lib/services/form-builder/*.spec.ts',
    '<rootDir>/src/lib/services/html-parser/*.spec.ts',
    '<rootDir>/src/lib/services/grid/*.spec.ts',
    '<rootDir>/src/lib/services/grid-layout/*.spec.ts',
    '<rootDir>/src/lib/services/grid-data-formatter/*.spec.ts',
    '<rootDir>/src/lib/services/download/*.spec.ts',
    '<rootDir>/src/lib/pipes/asset/*.spec.ts',
    '<rootDir>/src/lib/pipes/gradient/*.spec.ts',
    '<rootDir>/src/lib/pipes/readable-history-value/*.spec.ts',
    '<rootDir>/src/lib/components/layout/layout.component.spec.ts',
    '<rootDir>/src/lib/components/language-switch/language-switch.component.spec.ts',
    '<rootDir>/src/lib/components/record-history/*.spec.ts',
    '<rootDir>/src/lib/components/record-history/record-history-table/*.spec.ts',
    '<rootDir>/src/lib/components/record-history/record-history-cards/*.spec.ts',
    '<rootDir>/src/lib/components/field-history-question/*.spec.ts',
    '<rootDir>/src/lib/components/status-options/*.spec.ts',
    '<rootDir>/src/lib/components/form/form.component.spec.ts',
    '<rootDir>/src/lib/components/widgets/common/tab-actions/*.spec.ts',
    '<rootDir>/src/lib/components/widgets/common/tab-actions/read-only-fields-modal/*.spec.ts',
    '<rootDir>/src/lib/components/query-builder/tab-fields/*.spec.ts',
    '<rootDir>/src/lib/components/query-builder/tab-fields/form-filter/*.spec.ts',
    '<rootDir>/src/lib/components/ui/core-grid/*.spec.ts',
    '<rootDir>/src/lib/components/ui/core-grid/grid/*.spec.ts',
    '<rootDir>/src/lib/models/*.spec.ts',
    '<rootDir>/src/lib/survey/global-properties/*.spec.ts',
    '<rootDir>/src/lib/utils/*.spec.ts',
    '<rootDir>/src/lib/utils/filter/*.spec.ts',
    '<rootDir>/src/lib/utils/validators/*.spec.ts',
    '<rootDir>/src/lib/components/email/steps/schedule-alert/*.spec.ts',
    '<rootDir>/src/lib/components/email/steps/create-notification/*.spec.ts',
    '<rootDir>/src/lib/components/email/steps/layout/*.spec.ts',
    '<rootDir>/src/lib/components/email/email.component.spec.ts',
    '<rootDir>/src/lib/components/email/email.service.spec.ts',
    '<rootDir>/src/lib/components/email/steps/preview/*.spec.ts',
    '<rootDir>/src/lib/components/email/steps/select-distribution/*.spec.ts',
    '<rootDir>/src/lib/components/email/components/dataset-filter/*.spec.ts',
    '<rootDir>/src/lib/components/email/components/email-delivery/*.spec.ts',
    '<rootDir>/src/lib/components/email/components/ems-template/*.spec.ts',
    '<rootDir>/src/lib/components/filter/filter-row/*.spec.ts',
    '<rootDir>/src/lib/components/templates/components/preview-template-modal/*.spec.ts',
    '<rootDir>/src/lib/components/widgets/grid-settings/grid-settings.forms.spec.ts',
    '<rootDir>/src/lib/components/widgets/grid-settings/grid-action-settings/*.spec.ts',
    '<rootDir>/src/lib/components/widgets/grid/grid.component.spec.ts',
    '<rootDir>/src/lib/services/email/*.spec.ts',
    '<rootDir>/src/lib/survey/components/resource.spec.ts',
    '<rootDir>/src/lib/survey/components/resources.spec.ts',
    '<rootDir>/src/lib/survey/components/field-history.spec.ts',
    '<rootDir>/src/lib/survey/components/utils/*.spec.ts',
    '<rootDir>/src/lib/survey/widgets/*.spec.ts',
    '<rootDir>/src/lib/survey/widgets/utils/*.spec.ts',
    '<rootDir>/src/lib/utils/*.spec.ts',
    '<rootDir>/src/lib/survey/triggers/*.spec.ts',
  ],
};
