#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

npm run check-i18n

git add libs/shared/src/i18n/en.json
git add libs/shared/src/i18n/fr.json
git add libs/shared/src/i18n/test.json
