name: Build

on:
  push:
    branches:
      - 'main'
      - 'release-*'
      - 'hotfix-*'
      - 'feature-*'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install Dependencies
        run: npm ci
      - name: Build Shared Library
        run: npm run build -- --prod safe
      - name: Build Back-office
        run: npm run build -- --configuration=azure-uat back-office
      - name: Build Front-office
        run: npm run build -- --configuration=azure-uat front-office
