name: Front-end CD Azure

on:
  push:
    branches:
      - 'azure'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name:
      run: npm ci
    - name: Build Shared Library
      run: npm run build safe
    - name: Build Back-office
      run: npm run build:az
    - name: Build Front-office
      run: npm run build:az front-office
    - name: Archive build Back-office
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: deploy_dist_back_office
        path: dist/back-office
    - name: Archive build Front-office
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: deploy_dist_front_office
        path: dist/front-office

  deploy_back_office_azure:
    name: Deploy Back-office
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: deploy_dist_back_office
        path: dist/back-office
    - name: Deploy on Azure
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob delete-batch --source '$web' --account-name safebackoffice --account-key ${{ secrets.ACCOUNT_KEY_BACK_OFFICE }}
          az storage blob upload-batch -s dist/back-office/ -d '$web' --account-name safebackoffice --account-key ${{ secrets.ACCOUNT_KEY_BACK_OFFICE }}

  deploy_front_office_azure:
    name: Deploy Front-office
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: deploy_dist_front_office
        path: dist/front-office
    - name: Deploy on Azure
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob delete-batch --source '$web' --account-name safefrontoffice --account-key ${{ secrets.ACCOUNT_KEY_FRONT_OFFICE }}
          az storage blob upload-batch -s dist/front-office/ -d '$web' --account-name safefrontoffice --account-key ${{ secrets.ACCOUNT_KEY_FRONT_OFFICE }}
