name: Trigger CD

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - environment: OORT_GUYANE
          #   ref: release-1.3.0-next
          - environment: OORT_PROD
            ref: release-1.3.0-next
          - environment: OORT_DEV
            ref: release-1.3.0-next
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dispatch CD Event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CD_ACCESS_TOKEN }}
          event-type: CD
          client-payload: '{"environment": "${{ matrix.environment }}", "ref": "${{ matrix.ref }}"}'
